labguage: generic

sudo: required # super user permission
services:
  - docker

before_install:
  - docker build -t tak113/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true tak113/docker-react-test npm run test -- --coverage
  # -  docker run tak113/docker-react-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2" # from aws url
  app: "docker-test" # same name from aws
  env: "Dockertest-env" # environmetn from aws
  bucket_name: "elasticbeanstalk-us-west-2-147528153165" # seach from S3 in aws
  bucket_path: "docker-test" # same name as app
  on:
    branch: master # master branch in github
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

