labguage: generic

sudo: required # super user permission
services:
  - docker

before_install:
  - docker build -t tak113/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true tak113/docker-react-test npm run test
  # -  docker run tak113/docker-react-test npm run test -- --coverage